version: 2
updates:
    - package-ecosystem: "maven"
      directory: "/"
      schedule:
        interval: "daily"
      target-branch: development
      default_labels: "dependabot"
      commit-message:
          prefix: "[DEPENDABOT]"
