language: java
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2/repository"
sudo: false
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    on_success: never
    on_failure: always
branches:
  only:
  - master
script:
- mvn --settings .travis.settings.xml clean cobertura:cobertura deploy
after_success:
- bash <(curl -s https://codecov.io/bash)
- mvn site
env:
  global:
  - secure: 00Nnx5VPkDhCBRvzag9lHNqwy+nE7TZAlCAqDbpNChmeUkrXu2LnkAbYyGRn4tAy5tmBYdYpDuH5wRT6mArF+5A7LrUkBh2pWnawMTDpvz4/rMe7kj+PK/e8OCCZQ4l+y2HxTGwQJc8B35heQj8n5N8wF48p4UheNuW0xpn58/2qgex9PWmLKGlz31ysGj8CzuDykJxX9XyiR3/eAUrePoyBosvMFJ2gbDFLIXmu7SHFrFLWL9sv10NpoC1vjtwzASyL+Q+ioLwvMiiSwnCGkpM+lSlHxIl86NJLme5bRUewb2QHekqMF/rLTK9JFAKC5j79iwv+f0bEPe3gr+VvSc6WW/fh7BO+hS+hNvIafueYsJJnlE0CSewbP9+VBD/XeKU3w0P9LjlVbYGN7G4fc/PlMcH79/i4jlcdqomFz4vgAGKXHxU/a/SSA40TXzCsAayeVPEdEfZUMNHAPceUdmcmfJKtcx5eQuS/jc6S3qbtjvIG+lXHQ/l6BlDcRU+LZ3BsgUAFhqtBcTkhKfJT4UdC9JmaSpGKFcfTJfi8Pv/ha8U+D/a78HQ0iU7kfic4zcpCWyxA1bLu0f+62qVQo/ZOFZh3C8uZrx/XObqm18W+68FIpPhdEZvdttjPb3WdV6hp9n9AQxve5NqjJHWy6hvwjG7XpqYtgPSzlwibuLo=
  - secure: IplF/eLMOXkDReSGP8/dOc9Oyz6B6rsaJERR/DOW+r2/BBEu1O91zhDDe4ujuUZa3StE+uX7IqybEzjTbjWyJujMqpczHTG43hAFm7A1kGnUkWvBN5K3/fHWnTyfu1cGgy/2/mVMXS3xw8cDXGuyyy9Jv5Pu8PpcDlGAy3cfR8ol6iw4GWVdvJOgLosHrCOKVQ87jdnX43SzJ9ac0+c+C5d9bpor2QT8d0fHGFRMqam7e69I3EE8dtx7TgALFo234ibvCkJd8QO/5xryHHWdfGIT32iNbEsoczxMsSKmFynFgfyCjUYohfh9rretRJZmI7t5lYB9RO9g91lEcNlDK1bXh+YBxOil7HG7zU5schnocMpayF+L0ceuYCYgUsd+nBaTzSbhUMzJvqBpTGoq43VRn4pYNsOyefDLShsLCMxuyp2pHEq23m9gGWQfCVdyyRKEvnR2gEvmdj7rLKQ8pFebUEBi9TAjH5krjNvELsDtAoINArEY4gfayJXRcrGP5FzW2T1mWQrap3nP44JaPNns2rue65U9OZPOnN8PiZugj4cHuf8rV/5bXijqvVdUy8h5/Pvc/WZ89v8GG+KgBF31R+rpguXga0M39uTw748tEQRzJdg7vYfmKxgilKRvAi5EW/MY86xDfHJ7u5aWm2jtW/v7drTnOJla/FSxk3M=
